### ISSUE TITLE
Error al intentar crear un usuario desde la pantalla del administrador #90 

### ISSUE THREAD

**Issue by earias08** [NachoFernandezCano/proyectoFinalRollingCode#103]
Proceso
Luego de loguearse como administrador, ingresamos a la tabla de usuarios e intentamos crear un nuevo usuario.

Resultado esperado
Crear un usuario con el perfil user, con datos correctos.

Resultado actual
al cargar los datos en el formulario no hay una limitacion de caracteres en el campo de Número y codigo postal. Ademas al presionar guardar aparece un error en la consola,  se ve en la imagen adjunta. Finalmente el usuario no fue creado

Captura
![image](https://github.com/NachoFernandezCano/proyectoFinalRollingCode/assets/18445151/0527bf5c-3d25-4e45-a7dc-37a6162fa3bc)

**Comment by earias08** [comment]
Resultado actual

Al crear el usuario, este no se visualiza en la tabla. Se debe recargar la pagina para visualizar el usuario creado

**Comment by emiarias** [comment]
Resuelto
