### ISSUE TITLE
Bajar el footer en paginas que no tienen mucho contenido

### ISSUE THREAD

**Issue by earias08** [NachoFernandezCano/proyectoFinalRollingCode#91]
Proceso
Al ingresar en paginas con poco contenido, por ejemplo cuando cargamos un producto al carrito se produce el error nombrado en la siguiente issue.

_Originally posted by @earias08 in https://github.com/NachoFernandezCano/proyectoFinalRollingCode/issues/74#issuecomment-1574004585_

Resultado esperado
Visualizar el footer al final de la web.

Captura

![image](https://user-images.githubusercontent.com/18445151/242939711-a5d89ad4-3cf4-491e-99b6-ed1fab519947.png)

**Comment by earias08** [comment]
@NachoFernandezCano esta issue se sigue visualizando como en la imagen adjunta en dispositivos grandes. 

![image](https://github.com/NachoFernandezCano/proyectoFinalRollingCode/assets/18445151/e32b6a2b-5a8a-4233-b397-ededd2667102)

**Comment by emiarias** [comment]
Resuelto
